### ISSUE TITLE
Notas de aprendizado / desenvolvimento

### ISSUE THREAD

**Issue by alexandre-mbm** [ENE/OptiKey#7]
@alandbm, segue um norte para prosseguirmos ajustando Tobii EyeX + OptoKey ao nosso pai:

**Dicionário**
- [ ] 1. Bug para se adicionar palavras com acentos ‒ OptiKey/OptiKey#300
- [ ] 2. Mexer ou criar prioridades (planilha)
- [ ] 3. Fazer backup

**WhatsApp ou edição**
- [x] 4. Selecionar palavra: `Control + A`
- [x] 5. Posicionar cursor: Teclas Físicas
- [x] 6. Mudar de linha: `Shift + Enter`
- [ ] 7. Frases recentes ‒ OptiKey/OptiKey#302
- [ ] 8. Mover cursor dentro da tela preta (conversação) ‒ OptiKey/OptiKey#301 → OptiKey/OptiKey#110
- [ ] 9. Teclado de favorito, incluindo acesso a frases favoritas ‒ OptiKey/OptiKey#303

**Tinytch**
- [ ] 10. Novos botões, novos comandos
- [ ] 11. Pulsador de mola (polegar)
- [ ] 12. Teste: DigiUSB + DigiKeyboard
- [ ] 13. Licenciamento de código para GitHub
- [ ] 14. Switch de alavanca
- [ ] 15. Sensores de vibração

**Tobii**
- [ ] 16. Testes com deslocamento (perguntar)

**OptiKey**

  _Ver também a seção "Segurança", mais adiante._

- [ ] 17. Opção de privacidade, comandando apagamento de telas
- [ ] 18. Atalhos de Unicode: travessão, dois-pontos, traço, barra, grau, etc.
- [ ] 19. Horas e utilidades?

**Instalação do hardware**
- [ ] 20. DR para a extensão ou para o suporte
- [ ] 21. Consertar caixas de som
- [ ] 22. Som do monitor é fraquinho mesmo? Ele tem duas entradas ou saídas.

**Backup, Git e scripts**
- [ ] 23. Configurações de Alberto
- [ ] 24. Dicionário de Alberto
- [ ] 25. Script para manipular atualizações de dicionário

**Conforto visual**
- [x] 26. Zoom 150% tem desvantagem de rolar ou ocultar cabeçalho ou rodapé do WhatsApp
- [x] 27. Zoom 125%
- [x] 28. Problema de tela invertida
```
Saída para > Telas clones > Tela integrada + televisão digital
Paisagem (virado)
Bloqueado / desbloqueado (toogle)
```

**Segurança**
- [ ] 29. Windows Hello
- [ ] 30. Digitação oculta de senhas, com os olhos!
